language: c++
sudo: required
notifications:
  email:
    recipients:
      - dagmcci@googlegroups.com
  slack: cnerg:d48My26ZXfvHlg0On2WwNQFi
env:
  matrix:
    # main
    - COMPILER="gcc-7"     MOAB_VERSION="5.0"    BUILD_GEANT4="ON"
    - COMPILER="clang-5.0" MOAB_VERSION="5.0"    BUILD_GEANT4="ON"
    # vary moab version
    - COMPILER="gcc-7"     MOAB_VERSION="master" BUILD_GEANT4="ON"
    - COMPILER="clang-5.0" MOAB_VERSION="master" BUILD_GEANT4="ON"
    # vary compiler
    - COMPILER="gcc-4.8"   MOAB_VERSION="5.0"    BUILD_GEANT4="OFF"
    - COMPILER="gcc-5"     MOAB_VERSION="5.0"    BUILD_GEANT4="OFF"
    - COMPILER="gcc-6"     MOAB_VERSION="5.0"    BUILD_GEANT4="OFF"
    - COMPILER="clang-4.0" MOAB_VERSION="5.0"    BUILD_GEANT4="OFF"
services:
  - docker
before_install:
  - sudo docker pull ljacobson64/dagmc-ci-ubuntu-16.04
  # get a container id
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "cd /root"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  # make the build directory
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "mkdir -p /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci-ubuntu-16.04
  # copy the repo in the docker instance
  - sudo docker cp ../DAGMC $commit_id:/root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci-ubuntu-16.04
  # build moab
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                  bash docker/build_moab.sh $COMPILER $MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci-ubuntu-16.04
install:
  # build dagmc (shared executables)
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                  bash docker/build_dagmc.sh $COMPILER OFF $MOAB_VERSION $BUILD_GEANT4"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci-ubuntu-16.04
  # build dagmc (static executables)
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                  bash docker/build_dagmc.sh $COMPILER ON $MOAB_VERSION $BUILD_GEANT4"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci-ubuntu-16.04
script:
  # run tests
  - sudo docker run ljacobson64/dagmc-ci-ubuntu-16.04 /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                  export TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST;
                                                                  export MW_REG_TEST_MODELS_URL=$MW_REG_TEST_MODELS_URL;
                                                                  bash docker/run_tests.sh $COMPILER $MOAB_VERSION $BUILD_GEANT4"
