language: c++
sudo: required
notifications:
  email:
    recipients:
      - dagmcci@googlegroups.com
  slack: cnerg:d48My26ZXfvHlg0On2WwNQFi
env:
  matrix:
    # main
    - COMPILER="gcc-5"     BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="gcc-5"     BUILD_STATIC="ON"  MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-4.0" BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-4.0" BUILD_STATIC="ON"  MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    # vary moab version
    - COMPILER="gcc-5"     BUILD_STATIC="OFF" MOAB_VERSION="master" GEANT4_VERSION="10.03.p01"
    - COMPILER="gcc-5"     BUILD_STATIC="ON"  MOAB_VERSION="master" GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-4.0" BUILD_STATIC="OFF" MOAB_VERSION="master" GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-4.0" BUILD_STATIC="ON"  MOAB_VERSION="master" GEANT4_VERSION="10.03.p01"
    # vary geant4 version
    - COMPILER="gcc-5"     BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.01.p03"
    - COMPILER="gcc-5"     BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.02.p03"
    # vary compiler
    - COMPILER="gcc-4.8"   BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="gcc-4.9"   BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="gcc-6"     BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-3.8" BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
    - COMPILER="clang-3.9" BUILD_STATIC="OFF" MOAB_VERSION="4.9.2"  GEANT4_VERSION="10.03.p01"
services:
  - docker
before_install:
  - sudo docker pull ljacobson64/dagmc-ci
  # get a container id
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  # make the build directory
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "mkdir -p /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
  # copy the repo in the docker instance
  - sudo docker cp ../DAGMC $commit_id:/root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
  # build moab
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                     bash docker/build_moab.sh $COMPILER $MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
install:
  # build dagmc
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                     bash docker/build_dagmc.sh $COMPILER $BUILD_STATIC $MOAB_VERSION $GEANT4_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
script:
  # run tests
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                     export TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST;
                                                     export MW_REG_TEST_MODELS_URL=$MW_REG_TEST_MODELS_URL;
                                                     bash docker/run_tests.sh $COMPILER $MOAB_VERSION $GEANT4_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
