language: c++
sudo: required
notifications:
  email:
    recipients:
      - dagmcci@googlegroups.com
  slack: cnerg:d48My26ZXfvHlg0On2WwNQFi
env: 
  matrix:
    # COMPILER="gcc-4.8"   MOAB_VERSION="4.9.2"
    # COMPILER="gcc-4.8"   MOAB_VERSION="master"
    # COMPILER="gcc-5"     MOAB_VERSION="4.9.2"
    # COMPILER="gcc-5"     MOAB_VERSION="master"
    - COMPILER="gcc-6"     MOAB_VERSION="4.9.2"
    # COMPILER="gcc-6"     MOAB_VERSION="master"
    # COMPILER="clang-3.8" MOAB_VERSION="4.9.2"
    # COMPILER="clang-3.8" MOAB_VERSION="master"
services:
  - docker
before_install:
  - sudo docker pull ljacobson64/dagmc-ci
  # to get a container id
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  # copy the repo in the docker instance
  - sudo docker cp ../DAGMC $commit_id:/root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
  # build moab
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC && \
                                                     ./.build_moab.sh $COMPILER $MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
install:
  # build dagmc
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC && \
                                                     ./.build_dagmc.sh $COMPILER $MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
script:
  # run tests
  - sudo docker run ljacobson64/dagmc-ci /bin/sh -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC && \
                                                     export TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST && \
                                                     export MW_REG_TEST_MODELS_URL=$MW_REG_TEST_MODELS_URL && \
                                                     ./.run_tests.sh"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id ljacobson64/dagmc-ci
