language: c++
sudo: false
addons:
  apt:
    packages:
    - gfortran 
    - g++ 
    - build-essential 
    - cmake 
    - libblas-dev 
    - liblapack-dev
before_install:
  # build cmake
  - git clone git://cmake.org/cmake.git
  - cd cmake
  - git checkout master
  - mkdir bld
  - cd bld
  - cmake ../. -DCMAKE_INSTALL_PREFIX=$HOME/cmake
  - make -j2 > log-file 2>&1
  - make install
  - export PATH="$HOME/cmake/bin:$PATH"
  - cd ..
  - cd .. 
  # build hdf5
  - wget https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz
  - tar -zxf hdf5-1.8.13.tar.gz
  - mv hdf5-1.8.13 hdf5
  - cd hdf5
  - mkdir bld
  - cd bld
  - ../configure --enable-shared --disable-debug --enable-optimize --prefix=$HOME/hdf5
  - make -j2 > log-file 2>&1
  - make install
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/hdf5/lib/"
  - export PATH="$HOME/hdf5/bin:$PATH"
  - cd ..
  - cd ..
  # build moab
  - git clone https://bitbucket.org/fathomteam/moab
  - cd moab
  - git checkout master
  - autoreconf -fi
  - mkdir bld
  - cd bld
  - ../configure --enable-dagmc --enable-shared --disable-debug --enable-optimize --with-hdf5=$HOME/hdf5 --prefix=$HOME/moab
  - make -j2 > log-file 2>&1
  - make install
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/moab/lib/"
  - export PATH="$HOME/moab/bin:$PATH"
  - cd ..
  - cd ..
  # build geant4
  - wget http://geant4.cern.ch/support/source/geant4.10.00.p02.tar.gz
  - tar -zxf geant4.10.00.p02.tar.gz
  - cd geant4.10.00.p02
  - mkdir bld
  - cd bld
  - cmake ../. -DCMAKE_INSTALL_PREFIX=$HOME/geant4.10.00.p02
  # geant4 compile takes 30 mins so need to use travis_wait
  - travis_wait make -j2
  - make install
  - export PATH="$HOME/geant4.10.00.p02/bin:$PATH"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/geant4.10.00.p02/lib/"
  - cd ..
  - cd ..
install:
  # build dagmc
  # - cd DAGMC
  - mkdir bld
  - cd bld
  - cmake ../. -DBUILD_GEANT4=ON -DGEANT4_DIR=$HOME/geant4 -DCMAKE_INSTALL_PREFIX=$HOME/DAGMC
  - make 
  - make install
  - cd ..
script:
  # move to test dir
  - cd tests
  # run each test
  - ./dagsolid_unit_tests
  - ./fludag_unit_tests
  - ./test_CellTally
  - ./test_KDEKernel
  - ./test_KDEMeshTally
  - ./test_KDENeighborhood
  - ./test_PolynomialKernel
  - ./test_Quadrature
  - ./test_Tally
  - ./test_TallyData
  - ./test_TallyEvent
  - ./test_TrackLengthMeshTally
  - ./uwuw_unit_tests
  - ./uwuw_unit_tests_tally
